
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WassetPortal_DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Action
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Action()
    {

        this.UserActions = new HashSet<UserAction>();

    }


    public int ActionID { get; set; }

    public string ActionName { get; set; }

    public string Description { get; set; }

    public Nullable<bool> ActionStatus { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserAction> UserActions { get; set; }

}

}
