
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WassetPortal_DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Hospitals_Packages
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Hospitals_Packages()
    {

        this.Patients = new HashSet<Patient>();

    }


    public int Hospitals_PackagesID { get; set; }

    public Nullable<int> Fk_Hospital_ID { get; set; }

    public Nullable<int> Fk_Package_ID { get; set; }

    public Nullable<bool> Hospital_Package_Status { get; set; }

    public Nullable<decimal> Price { get; set; }



    public virtual Hospital Hospital { get; set; }

    public virtual Test Test { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Patient> Patients { get; set; }

}

}
