//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WassetPortal_DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string PASSPORT { get; set; }
        public string ID_IQAMA { get; set; }
        public string NATIONALITY { get; set; }
        public string Gender { get; set; }
        public string DOB { get; set; }
        public string MOBILE { get; set; }
        public string HESN_NO { get; set; }
        public string C_Case { get; set; }
    }
}
