
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WassetPortal_DAL.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Test
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Test()
    {

        this.Hospitals_Packages = new HashSet<Hospitals_Packages>();

    }


    public int TestID { get; set; }

    public string TestNameEn { get; set; }

    public string TestNameAr { get; set; }

    public string TestCode { get; set; }

    public Nullable<bool> Test_status { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Hospitals_Packages> Hospitals_Packages { get; set; }

}

}
